### ISSUE TITLE
When 'cheating', app crashes to white screen

### ISSUE THREAD

**Issue by naxels** [elias94/tryclojure#10]
Thank you for making this! Provides good insight into how a ClojureScript app works for a beginner like me.

While trying out running the code myself, I discovered that you could you `(next-step)` after `(start)`
to progress the app.

If you enter `(next-step)` a couple of times, the screen will go white because the app crashes since no `:user-name` is set.

Obviously nobody should run into this, but I think it would be fun to add a default `:user-name`
to show that someone has found a hidden "Gem".

**Comment by elias94** [comment]
Thanks for testing and the hint! I decided to go for **Young Clojurian** as default user.
