### ISSUE TITLE
bug(tutorial): "Range of N" incorrectly describes max value

### ISSUE THREAD

**Issue by cduplantis** [elias94/tryclojure#15]
The tutorial states:
      So `(range 5)` will return numbers from 0 to **5**. Use `(doc range)` to print
This should read:
      So `(range 5)` will return numbers from 0 to **4**. Use `(doc range)` to print"

https://github.com/elias94/tryclojure/blob/579bb75fba486702d202462ece5f753a3b604ab8/src/app/tutorial.cljs#L141

**Comment by elias94** [comment]
Thanks for the fix!
