### ISSUE TITLE
it does not like "(range)"

### ISSUE THREAD

**Issue by behrica** [elias94/tryclojure#9]
obviously ...

**Comment by borkdude** [comment]
Perhaps using `*print-length*` will work:

```
user=>  (binding [*print-length* 20] (pr-str (range)))
"(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...)"
```

**Comment by borkdude** [comment]
#11 should fix this

**Comment by borkdude** [comment]
<img width="533" alt="Screen Shot 2022-02-22 at 23 21 50" src="https://user-images.githubusercontent.com/284934/155229494-949dcd2a-6e5e-45b1-ac37-cf6b6f49cf7e.png">
